### PR TITLE
Do not compare Boxed values with identity comparison

### PR DESCRIPTION
**Pull request by Shredder121**

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the report! You are right this was an issue. I changed the fix a little bit because I was not keen on adding apache commons as a direct dependency for something so simple. I also added some tests. See https://github.com/pivotalsoftware/pivotal-cla/commit/2ff81d4566eb98aed6064c0dea638dc60dfba9ff for details

**Comment by Shredder121** [comment]
That's fine, I at least wanted a clean patch.
:+1:

**Comment by rwinch** [comment]
Just wanted to let you know that I modified things (doesn't hurt to get a second set of eyes on it) :)

**Comment by Shredder121** [comment]
That's true, looks good though!

**Pull request closed without merging**
