### PR TITLE
Fix proofreading warnings

### PR DESCRIPTION
**Pull request by Shredder121**
I think the title says enough.
There were some issues/typos in the CCLA text.

### CODE REVIEW

**Comment by rwinch** [comment]
@Shredder121 Thanks for the PR! 

Unfortuantely we cannot merge this as is because it will break in production. This will happen because this schema was already merged and there is a table that validates the checksum. We need a new SQL file that will update the table to the new values. Any chance you could provide this?

**Comment by Shredder121** [comment]
AH! Yes that makes sense.
What naming should I use?
Is it still V1, or V2?

**Comment by rwinch** [comment]
Thanks for the fast reply. Let's go with `V1_3__fix-typos.sql`

**Comment by Shredder121** [comment]
I added a new file with the contents of the previous file with the typos fixed.
You can verify using this command:

``` bash
$ git show 6cb0b03c29efe0070d88e914aeba500318967612--find-copies-harder
```

Or optionally, to minimize the diff:

``` bash
$ git show 6cb0b03c29efe0070d88e914aeba500318967612--find-copies-harder --color-words
```

_EDIT: new sha hash for the commit._

**Comment by Shredder121** [comment]
I would appreciate it if you could comment on my syntax.
I wasn't quite sure about that `name` parameter.
Usually that's an SQL keyword, so if I have to quote anything in a specific way, then let me know.
Locally it works for me, so I can't quite tell.

**Comment by rwinch** [comment]
@Shredder121 Thanks for the update! This is merged via 6cb0b03c29efe0070d88e914aeba500318967612

> You can verify using this command

Thanks for the tip. I use Beyond Compare for stuff like this :)

> Usually that's an SQL keyword, so if I have to quote anything in a specific way, then let me know.
> Locally it works for me, so I can't quite tell.

It works fine for me and tested fine in our staging environment. This is now pushed to master so it will build and deploy to prod shortly.

Thanks again!

**Comment by Shredder121** [comment]
> Thanks for the tip. I use Beyond Compare for stuff like this :)

No problem, I just wanted to give you a pointer on how to verify my copy-paste work.
But another tool is fine as well.

> It works fine for me and tested fine in our staging environment.

Yes, locally I saw the same, but I wasn't sure on whether it would deploy or not.
Good to hear/see that it did!

Thank you as well, for your time!

**Pull request closed without merging**
